
import com.sun.istack.internal.logging.Logger;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author macbookair
 */
public class ConsultaProductos extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaProductos
     */
    Conexion mConexion = new Conexion();
    Producto mProducto = new Producto();
    DefaultTableModel Tabla = new DefaultTableModel();
    int ContadorColumna = 1;

    public ConsultaProductos() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TXTProductoBuscar = new javax.swing.JTextField();
        BTNSalir = new javax.swing.JButton();
        BTNBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TBLProductos = new javax.swing.JTable();
        BTNBuscarUno = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID Producto");

        BTNSalir.setText("Salir");
        BTNSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSalirActionPerformed(evt);
            }
        });

        BTNBuscar.setText("Buscar Todo");
        BTNBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarActionPerformed(evt);
            }
        });

        TBLProductos.setModel(Tabla);
        jScrollPane1.setViewportView(TBLProductos);

        BTNBuscarUno.setText("Buscar por ID");
        BTNBuscarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNBuscarUnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(TXTProductoBuscar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BTNSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTNBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(BTNBuscarUno))
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TXTProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTNBuscarUno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNSalir)
                        .addContainerGap(282, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(14, 14, 14))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BTNSalirActionPerformed

    private void BTNBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel TablaLimpiar = (DefaultTableModel) TBLProductos.getModel();
        int a = TBLProductos.getRowCount()-1;
        for(int i = a; i>=0;i--) {
            TablaLimpiar.removeRow(TablaLimpiar.getRowCount()-1);
        }
        
        if (mConexion.con()) {
            ArrayList mArrayList = new ArrayList();
            mArrayList = mConexion.ConsultaTodoProducto();
            String[] Datos = null;
            if (mArrayList != null) {
                if (ContadorColumna == 1) {
                    Tabla.addColumn("ID");
                    Tabla.addColumn("Nombre");
                    Tabla.addColumn("Precio Compra");
                    Tabla.addColumn("Precio Venta");
                    Tabla.addColumn("Fecha Caducidad");
                    Tabla.addColumn("ID Proveedor");
                    Tabla.addColumn("Cantidad");
                    ContadorColumna = 2;
                }
                for (int i = 0; i < mArrayList.size(); i++) {
                    mProducto = (Producto) mArrayList.get(i);
                    Datos = new String[7];
                    Datos[0] = "" + mProducto.getIDProducto();
                    Datos[1] = mProducto.getNombreProducto();
                    Datos[2] = "" + mProducto.getPrecioProducto();
                    Datos[3] = "" + mProducto.getPrecioVentaProducto();
                    Datos[4] = mProducto.getFechaCaducidad();
                    Datos[5] = "" + mProducto.getProveedor_idProveedor();
                    Datos[6] = "" + mProducto.getCantidadProducto();
                    Tabla.addRow(Datos);
                }

            } else {
                JOptionPane.showMessageDialog(null, "No existe ese Producto...");
            }
            this.TBLProductos = new javax.swing.JTable();
            this.TBLProductos.setModel(Tabla);
            this.TBLProductos.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBLProductos.getColumnModel().getColumn(1).setPreferredWidth(100);
            this.TBLProductos.getColumnModel().getColumn(2).setPreferredWidth(400);
            this.TBLProductos.getColumnModel().getColumn(3).setPreferredWidth(600);
            this.TBLProductos.getColumnModel().getColumn(4).setPreferredWidth(400);
            this.TBLProductos.getColumnModel().getColumn(5).setPreferredWidth(100);
            this.TBLProductos.getColumnModel().getColumn(6).setPreferredWidth(100);
            if (this.TBLProductos.getRowCount() > 0) {
                this.TBLProductos.setRowSelectionInterval(0, 0);
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Error al consultar");
        }
        mConexion.desconectar();
    }//GEN-LAST:event_BTNBuscarActionPerformed

    private void BTNBuscarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNBuscarUnoActionPerformed
        // TODO add your handling code here:
        try {
        DefaultTableModel TablaLimpiar = (DefaultTableModel) TBLProductos.getModel();
        int a = TBLProductos.getRowCount()-1;
        for(int i = a; i>=0;i--) {
            TablaLimpiar.removeRow(TablaLimpiar.getRowCount()-1);
        }
            
        if(mConexion.con()){
            Producto mProducto = mConexion.consultarProducto(Integer.parseInt(this.TXTProductoBuscar.getText()));
            String [] Datos;
            
        
            if (mProducto != null) {
                if(ContadorColumna == 1) {
                Tabla.addColumn("ID");
                Tabla.addColumn("Nombre");
                Tabla.addColumn("Precio Compra");
                Tabla.addColumn("Precio Venta");
                Tabla.addColumn("Fecha Caducidad");
                Tabla.addColumn("ID Proveedor");
                Tabla.addColumn("Cantidad");
                ContadorColumna=2;
                }
                       
                Datos = new String[7];
                
                Datos[0] = ""+ mProducto.getIDProducto();
                Datos[1] = mProducto.getNombreProducto();
                Datos[2] = "" + mProducto.getPrecioProducto();
                Datos[3] = "" + mProducto.getPrecioVentaProducto();
                Datos[4] = mProducto.getFechaCaducidad();
                Datos[5] = "" + mProducto.getProveedor_idProveedor();
                Datos[6] = "" + mProducto.getCantidadProducto();
            
                Tabla.addRow(Datos);
            } else {
                // No hay datos
                JOptionPane.showMessageDialog(null,"No existe ese Producto...");
            }
            this.TBLProductos = new javax.swing.JTable();
            this.TBLProductos.setModel(Tabla);
            this.TBLProductos.getColumnModel().getColumn(0).setPreferredWidth(50);
            this.TBLProductos.getColumnModel().getColumn(1).setPreferredWidth(100);
            this.TBLProductos.getColumnModel().getColumn(2).setPreferredWidth(400);
            this.TBLProductos.getColumnModel().getColumn(3).setPreferredWidth(600);
            this.TBLProductos.getColumnModel().getColumn(4).setPreferredWidth(400);
            this.TBLProductos.getColumnModel().getColumn(5).setPreferredWidth(100);
            this.TBLProductos.getColumnModel().getColumn(6).setPreferredWidth(100);
            if (this.TBLProductos.getRowCount() > 0) {
                this.TBLProductos.setRowSelectionInterval(0, 0);
                }
            } else {
                JOptionPane.showMessageDialog(null,"Error al consultar");
                }
            mConexion.desconectar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"LLENAR EL CAMPIO");
        }
    }//GEN-LAST:event_BTNBuscarUnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaProductos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaProductos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNBuscar;
    private javax.swing.JButton BTNBuscarUno;
    private javax.swing.JButton BTNSalir;
    private javax.swing.JTable TBLProductos;
    private javax.swing.JTextField TXTProductoBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
